import States from "./Context/Contextapi";
import "./globals.css";

export const metadata = {
  title: "Form Data Parser App",
  description: "Generated by NextJS and NodeJS",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <States>
          {children}
        </States>
      </body>
    </html>
  );
}
